"""configbot

Revision ID: a1492aa05a4c
Revises: 8e963e1cd534
Create Date: 2025-09-16 13:24:54.640324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1492aa05a4c'
down_revision: Union[str, None] = '8e963e1cd534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token_key', sa.Text(), nullable=False),
    sa.Column('id_token_key', sa.Text(), nullable=False),
    sa.Column('access_token_json', sa.Text(), nullable=True),
    sa.Column('id_token_json', sa.Text(), nullable=True),
    sa.Column('sso_token', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='bot_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_config')
    # ### end Alembic commands ###
